### ISSUE TITLE
TEXT_VIEW_FACING is rendered incorrectly

### ISSUE THREAD

**Issue by sonyaa** [RobotWebTools/ros3djs#103]
I'm publishing a TEXT_VIEW_FACING marker. In the browser it's displayed as a 3D object, not as view-facing text.

Here's what is displayed in rviz:
![rviz_text](https://cloud.githubusercontent.com/assets/6108821/6335113/04aa2726-bb4e-11e4-8dde-33a4e9d14a3e.jpg)

Here's what is displayed in the browser:
![browser_text](https://cloud.githubusercontent.com/assets/6108821/6335112/048c1010-bb4e-11e4-86c6-e09fd671ed0a.jpg)

It's a simple visualization marker:
```    
marker_publisher.publish(Marker(type=Marker.TEXT_VIEW_FACING,
                            id=1, scale=Vector3(0.06, 0.06, 0.06),
                            lifetime=rospy.Duration(1),
                            text='View-facing text',
                            color=ColorRGBA(100, 100, 0, 1.0),
                            header=Header(frame_id='base_link'),
                            pose=Pose(Point(0,0,0), Quaternion(0, 0, 0, 1))))
```

(Another minor issue is that it will only work if I include a typeface font script - it seems to me that it should be included automatically. I expected all the markers to work as usual after I included ros3djs and its dependencies, and it took me a while to find the reason the text wasn't displayed.)

**Comment by rctoris** [comment]
Related to https://github.com/RobotWebTools/ros3djs/issues/29
