### ISSUE TITLE
Removed Markers cause Leak, being held by tfClient tf cbs

### ISSUE THREAD

**Issue by rethink-rlinsalata** [RobotWebTools/ros3djs#105]
There is a memory leak when trying to remove Markers, which seems to be caused by the callback functions of tfClient retaining a reference to the SceneNode.

Also, any Markers that return 'false' for the 'update' function (esp. things for which update() hasn't been implemented yet, like LINE_LIST), will cause a leak on every Marker message coming in, even if it's just a Marker publisher publishing the same marker w/o changes in a loop.
https://github.com/RobotWebTools/ros3djs/blob/0.13.0/src/markers/MarkerArrayClient.js#L51

It would basically seem like anything in the MarkerArrayClient's topic subscribe function that's trying to do a `rootObject.remove(...)` should also be handling removing the tf `cbs` references (possibly just unsubscribing?).

This could apply to anything with a TF callback.

I'm not 100% certain the tfClient is the only Retainer of the objects, but there is definitely a leak, and this is one of the retainers hanging around with a reference to `ROS3D.SceneNode` objects when they are no longer in `MarkerArrayClient.markers`.  I saw this by looking at Heap Snapshots in the Profiles tab of Chrome.  You can test it by publishing Markers and then publishing the "DELETE" action, or you can test the `updated` leak by just publishing a LINE_LIST type marker in a loop.

(FYI: I saw this in the latest code of `develop`, but used 0.13.0 tags in my links so the line #'s won't change.)

**Comment by MatthijsBurgh** [comment]
Fixed in https://github.com/RobotWebTools/ros3djs/pull/303
