### ISSUE TITLE
Make the library available on bower?

### ISSUE THREAD

**Issue by damiencaselli** [RobotWebTools/ros3djs#126]
Hi,

This is a feature request, not a real issue.

Having the library available using `bower install ros3djs` would make it much easier to maintain project dependencies and releases.

[Registering](http://bower.io/docs/creating-packages/#register) and updating package requires some extra steps that only owners (or contributors) of the repository should do, but I think this would really be worth it.

**Comment by Rayman** [comment]
Don't need push access for registering a bower package. Only to unregister it. I went ahead and did it for you. The names without *js* are preferred.
```
roslib git://github.com/RobotWebTools/roslibjs.git
roslibjs git://github.com/RobotWebTools/roslibjs.git
ros2d git://github.com/RobotWebTools/ros2djs.git
ros2djs git://github.com/RobotWebTools/ros2djs.git
ros3d git://github.com/RobotWebTools/ros3djs.git
ros3djs git://github.com/RobotWebTools/ros3djs.git
```
Now someone has to make a proper `bower.json` for ros3djs and it should work. I'll look into that if I find some time.
