### ISSUE TITLE
ros3djs tutorial needs a small fix

### ISSUE THREAD

**Issue by crunchex** [RobotWebTools/ros3djs#130]
I believe this tutorial needs a small fix: http://wiki.ros.org/ros3djs/Tutorials/VisualizingAURDF

The `<head>` in the supplied HTML code needs the THREE.STLLoader dependency.
Suggestion as follows:

```html
<script src="http://cdn.robotwebtools.org/threejs/current/STLLoader.min.js"></script>
```

**Comment by rctoris** [comment]
All set!
