### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by T045T** [RobotWebTools/ros3djs#140]
The test suite in roslibjs is great and very helpful.
I've lost track of how many times I had to fix a "fix" I made because there weren't any regression tests to alert me to my mistakes before pushing.

I'll try to set some time aside to start a test suite for ros3djs, but if anyone wants to beat me to it, you're very welcome! ;)

**Comment by rctoris** [comment]
:+1: :+1: :+1: This would be awesome!
