### ISSUE TITLE
Generate New Documentation

### ISSUE THREAD

**Issue by DLu** [RobotWebTools/ros3djs#147]
The [documentation](http://robotwebtools.org/jsdoc/ros3djs/current/) does not include all the classes added in the [current version](http://cdn.robotwebtools.org/ros3djs/current/ros3d.js) and was last generated  Mar 27 2015

**Comment by jihoonl** [comment]
New documentation should now point to the current version.(0.18.0)

* http://robotwebtools.org/jsdoc/ros3djs/current/
* https://static.robotwebtools.org/ros3djs/current/ros3d.js
