### ISSUE TITLE
Can't access fallbackTarget from outside Viewer

### ISSUE THREAD

**Issue by pbuteau** [RobotWebTools/ros3djs#165]
I'm using custom events on mouseHandler and I can't access the fallbackTarget because mouseHandler is not an object property of Viewer, why not making it ? I propose something like this.mouseHandler = new ROS3D.MouseHandler({
    renderer : this.renderer,
    camera : this.camera,
    rootObject : this.selectableObjects,
    fallbackTarget : this.cameraControls
  });
Instead of var mouseHandler = new....

**Comment by T045T** [comment]
Fixed in #169
