### ISSUE TITLE
Marker text color not displayed

### ISSUE THREAD

**Issue by 3Dmizu** [RobotWebTools/ros3djs#191]
Hi.
I wrote this code that it shows 3D text on 3D viewer.
https://gist.github.com/3Dmizu/630a94d3f6bd6ae9cfdbbb8fea7f9504

But text color doesn't change on browser using ROS3DJS even though it show correctly on rviz.
![ros3djs](https://user-images.githubusercontent.com/30615181/28810560-57fb1252-76c5-11e7-95be-6814689fb3ca.png)
![rviz](https://user-images.githubusercontent.com/30615181/28810563-5dd2d67e-76c5-11e7-849f-81ca56d168b5.png)

Thanks.

**Comment by jihoonl** [comment]
#188 should have fixed this issue. Can you try with the latest version?

**Comment by 3Dmizu** [comment]
Sorry I missed that post.
I have used REVISION:"0.16.0", so I replaced REVISION:"0.17.0-SNAPSHOT" and it works well.

Thank you.
