### ISSUE TITLE
EventEmitter2 dependency not specified in `package.json`

### ISSUE THREAD

**Issue by goretkin** [RobotWebTools/ros3djs#194]
The code depends on EventEmitter2 (e.g. https://github.com/RobotWebTools/ros3djs/blob/2f2ae47fa283d06a1a48c858fa82f60af483a10b/build/ros3d.js#L1313) 

(roslibjs does specify the dependency and so it's included in the build: https://github.com/RobotWebTools/roslibjs/blob/e0d67d1fcd7f48b978ed00d059bf9d34ac6eec81/build/roslib.js#L3)

I see the dependency is specified in `bower.js`. Is this intentional?

**Comment by jihoonl** [comment]
Probably not. It is just uncaught dependency that nobody noticed. Would you create a PR to fix it? :)

**Comment by T045T** [comment]
after merging #202, ```eventemitter2``` is now in ```package.js```
