### ISSUE TITLE
get rid of https://upload.wikimedia.org/wikipedia/commons/a/a2/Pixel-white.png

### ISSUE THREAD

**Issue by ensonic** [RobotWebTools/ros3djs#195]
What about using a dataurl instead of referencing the pixel from wikimedia:
Using http://png-pixel.com/ the replacement would be:

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=

The wikimedia url is used in two files.

**Comment by jihoonl** [comment]
[sensors/Particles.js](https://github.com/RobotWebTools/ros3djs/blob/develop/src/sensors/Particles.js#L20) uses the wikimedia url.

**Comment by jihoonl** [comment]
I will mark it as help wanted.

**Comment by MatthijsBurgh** [comment]
This is fixed by #218
