### ISSUE TITLE
How do I use this library properly using es6 import - npm

### ISSUE THREAD

**Issue by reinzor** [RobotWebTools/ros3djs#197]
I tried installing this package using npm:

    npm install --save git://github.com/RobotWebTools/ros3djs.git#develop

and then import

    import ROS3D from 'ros3d'

However, this is not working, can somebody help?

**Comment by rivertam** [comment]
You should really give more details in your issues. Are you getting an error message? Is it not compiling? Are you using a compiler like webpack? What node version are you using? Generally, if an issue contains "not working" in it, it's not giving enough detail.

That said, I can spot right away you're importing 'ros3d' instead of 'ros3djs' which is at least one problem.

**Comment by sevenbitbyte** [comment]
Hi @reinzor just wanted to point out that the package is released to npm at: https://www.npmjs.com/package/@robot-web-tools/ros3djs

Please let me know if you encounter any issues with the npm release we've just started publishing there.

**Comment by jihoonl** [comment]
Can try `npm install ros3d?`. I have confirmed that it downloads modules.

![module](https://user-images.githubusercontent.com/1556736/35113791-9448bb4a-fc37-11e7-9d11-a387bfa16c68.png)

**Comment by bvobart** [comment]
@jihoonl Yes, it downloads modules, but when importing the module, the imported object stays empty. I have gone through the trouble of creating *two* minimal working examples: one with create-react-app as I mentioned in my previous comment, and the other as basic as possible plain JavaScript launched with NodeJS. Both show the same problem.

Try it yourself: https://github.com/bvobart/ROS3D-NPM-MWE

**Comment by keego** [comment]
@bvobart I also have the same problem. It looks like the main issue is [how the ROS3D module is exported](https://github.com/RobotWebTools/ros3djs/blob/develop/src/Ros3D.js#L6), namely that it *isnt*. Simply `export`ing `ROS3D` worked for me but that's a breaking change. 

@sevenbitbyte @jihoonl Would you guys be down to follow the recommended `pkg.module` route [suggested by the guys over at Rollup](https://github.com/rollup/rollup/wiki/pkg.module)? If so I already have the recommended changes tested and in my forked branch, which I can gladly throw into a PR :)

**Comment by sevenbitbyte** [comment]
@keego Whoops great catch on the missing export! if you already have a fix please PR that so we can get this fixed for everyone.

The rollup approach looks like the right future proof thing to do to me. Seems like both changes should not have any adverse affects as this is the first time ros3djs has been pushed to NPM and clearly has not been usable as of yet.
