### ISSUE TITLE
CDN links not working

### ISSUE THREAD

**Issue by sausax** [RobotWebTools/ros3djs#199]
I am getting access denied when trying to use the CDN links

**Comment by dkorobov2** [comment]
I have the same problem...

**Comment by jihoonl** [comment]
RWT CDN and demo server are currently experiencing hosting issue. I suggest to host them locally or directly from github for now. I will post in the mailing list as soon as I get some conclusion.
See this thread : https://groups.google.com/d/msg/robot-web-tools/PlW1ECoL91Y/1ss6BPp_DAAJ

**Comment by jihoonl** [comment]
ah yes.. I couldn't find the same version that we uploaded in CDN..

**Comment by Faibk** [comment]
It seems like ColladaLoader2 has become the only ColladaLoader on three.js, when I just use the loader bundled with three.js everything seems to work fine...

**Comment by Faibk** [comment]
That's the one btw:
[colladaloader2.zip](https://github.com/RobotWebTools/ros3djs/files/1488141/colladaloader2.zip)

**Comment by jihoonl** [comment]
Awesome thanks Faibk.

**Comment by jihoonl** [comment]
All links should work as of now. I have uploaded all updated modules in the new cdn(https://static.robotwebtools.org/xxxx).

Reopen this issue if anything is missing.

**Comment by duwudi** [comment]
Seems the ColladaLoader CDN links are dead again, will this be resolved or should I just load them locally?
