### ISSUE TITLE
PointCloud2 doesn't display any colors

### ISSUE THREAD

**Issue by pap-x** [RobotWebTools/ros3djs#225]
Hello, I'm trying to display a pointcloud using the basic PointCloud2 function arguments but the colors are not displayed at all or they are all black for some reason. I think it may have to do with the color mapping function. Any ideas?
![screenshot from 2018-05-18 16-14-18](https://user-images.githubusercontent.com/1280891/40236849-79caee44-5ab7-11e8-995e-2b17e24f2ba5.png)

**Comment by pap-x** [comment]
Sorry guys, my pointcloud had a wrong datatype, that's why it couldn't display the colors.

**Comment by neweirik** [comment]
How did you solve it?  My data is structured like this
 ```cpp 
    pointCoud.fields.resize(4);
    pointCoud.fields[0].name = "x";
    pointCoud.fields[0].offset = 0;
    pointCoud.fields[0].datatype = sensor_msgs::PointField::FLOAT32;
    pointCoud.fields[0].count = 1;
    pointCoud.fields[1].name = "y";
    pointCoud.fields[1].offset = sizeof(float);
    pointCoud.fields[1].datatype = sensor_msgs::PointField::FLOAT32;
    pointCoud.fields[1].count = 1;
    pointCoud.fields[2].name = "z";
    pointCoud.fields[2].offset = 2 * sizeof(float);
    pointCoud.fields[2].datatype = sensor_msgs::PointField::FLOAT32;
    pointCoud.fields[2].count = 1;
    pointCoud.fields[3].name = "rgb";
    pointCoud.fields[3].offset = 3 * sizeof(float);
    pointCoud.fields[3].datatype = sensor_msgs::PointField::FLOAT32;
    pointCoud.fields[3].count = 1;
    pointCoud.data.resize(pointCoud.point_step*pointCoud.width*pointCoud.height);

```

And Rviz displays with color, but ros3d is just black

**Comment by jubeira** [comment]
@neweirik have you tried setting `colorsrc` to `rgb` when you create the `PointCloud2`?

```
    var cloudClient = new ROS3D.PointCloud2({
        ros: ros,
        tfClient: tfClient,
        rootObject: viewer.scene,
        topic: '/pointcloud_topic',
        material: { size: 0.05},
        colorsrc: 'rgb'
    });
```

**Comment by neweirik** [comment]
Hi! It did now work. You can find a bag file with my pointcloud [here](https://github.com/eirik-strand/scanner/tree/master/bags). 
And here are some pictures of how it looks in rwis and in ros3d 

![ros3d](https://user-images.githubusercontent.com/6408600/55025965-42a86680-5002-11e9-9ed0-6b3609b8b2f0.png)

![rviz](https://user-images.githubusercontent.com/6408600/55025969-44722a00-5002-11e9-88fa-7affc2332c56.png)


My client looks like this 
 ```javascript 
 var cloudClient = new ROS3D.PointCloud2({
      ros: ros,
      tfClient: tfClient,
      rootObject: viewer.scene,
      topic: '/nscan/scan',
      material: { size: 0.01},
      colorsrc: 'rgb',
      max_pts: 10000000
    });
 ```

**Comment by jubeira** [comment]
I'm seeing similar things with pointclouds on my end; actually the pointcloud from the first image is all white and doesn't have the same colors as the second one. I'm also using `rgb` as `colorsrc` and the metadata of my pointcloud looks like this:

```
height: 480
width: 640
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "rgb"
    offset: 16
    datatype: 7
    count: 1
is_bigendian: False
point_step: 32
row_step: 20480
```

Here's the view in `rviz`:
![Screenshot from 2019-03-26 16-14-29 (another copy)](https://user-images.githubusercontent.com/2480899/55026986-ee41be80-4fe2-11e9-8631-c0d89269044d.png)

And here's the view with `ros3djs`:
![Screenshot from 2019-03-26 16-14-29 (copy)](https://user-images.githubusercontent.com/2480899/55026996-f4d03600-4fe2-11e9-8d67-c0742fbdf67d.png)

@pap-x could you share what you did to solve the issue back then?

**Comment by jubeira** [comment]
For the record, the problem in my case was the color's encoding; the solution can be found [here](https://github.com/osrf/polymer-ros-rviz/pull/24#issuecomment-477771585).

**Comment by raphaelVig** [comment]
@jubeira  @neweirik  Did you have any issues with having some of the Point that have no color attached but the others are fine ?

As it is on the picture below ? 

![pointcloud2_interface](https://user-images.githubusercontent.com/86229590/165954232-c73a21da-0896-4615-afc2-1b79ac5c3730.PNG)

**Comment by jubeira** [comment]
Hi! Not that I remember.
Have you seen the patch in https://github.com/RobotWebTools/ros3djs/issues/225#issuecomment-478594071? (i.e. this PR here https://github.com/osrf/polymer-ros-rviz/pull/24).

You might be having an issue with the encoding of the color; the data might have been encoded in a different format than what this library is expecting. What I did back then to find a solution was opening the pointcloud in RViz (which displayed it properly) and finding the codepath to the function that decoded the pointcloud. RViz does a good job finding the right way of decoding the data; you may find something as well.
