### ISSUE TITLE
how to realize 2d pose estimate and 2d nav goal?

### ISSUE THREAD

**Issue by ydcool** [RobotWebTools/ros3djs#227]
or how to drag an arrow out in ros3djs like rviz does?

**Comment by Ydcool** [comment]
> any luck with it?

not yet ; ( 
I had change the way to interact with ros3d map for mobile page.

**Comment by rvipin17** [comment]
do you have any idea how to do pose estimate in ros3djs with a mouse click, just like we do in ros2djs?

**Comment by Ydcool** [comment]
> do you have any idea how to do pose estimate in ros3djs with a mouse click, just like we do in ros2djs?

not much, maybe you should learn more about three.js

**Comment by amy-fang** [comment]
Is there anything new here ?

**Comment by Robotec44** [comment]
Hi Guys 
Any updates in this case?
I know I can add this functionality with three.js  Raycaster object but I need some help with it. 
Some example or maybe code place where I can start
@rctoris  @DLu @T045T @jihoonl @J-Rojas

**Comment by MerAARIZOU** [comment]
@Robotec44 I suggest that you take a look at the Interactive Markers. I used them to manipulate a 7 DoF robot arm from a web page. From their 3D poses it was possible to calculate the IK and send the new path to the robot. [Here](http://wiki.ros.org/ros3djs/Tutorials/VisualizingInteractiveMarkers) is the tutorial about Interactive Markers in ROS3DJS

**Comment by Robotec44** [comment]
Thanks I check
