### ISSUE TITLE
Documentation on ROSwebsite outdated

### ISSUE THREAD

**Issue by WhatWhatz** [RobotWebTools/ros3djs#284]
Hi,
I noticed that the current API Documentation on the ROS website is outdated. Can you please update it. Second thing, I've noticed that the current Docu in src/visualization/Viewer.js has a little mistake in it. In the options to initialize a ROS3D.Viewer (line 27 in src/visualization/Viewer.js) the starting position of the camera option should be `cameraPose` and not `cameraPosition` as the Docu says (line 20vs.38 in src/visualization/Viewer.js). So this should be either changed in the Docu or the code.
Thank you !

**Comment by jihoonl** [comment]
I just updated the document version to `1.0.1`. It should be online soon.

https://github.com/RobotWebTools/robotwebtools.github.io/pull/74
