### ISSUE TITLE
Mesh Resource rendering changes after viewer click

### ISSUE THREAD

**Issue by timhodgson12** [RobotWebTools/ros3djs#291]
I am trying to add a ros3d [mesh resource](http://robotwebtools.org/jsdoc/ros3djs/current/models_MeshResource.js.html) to a viewer scene. Instead of saving as an stl on the api I am sending the mesh data to the client. (Must maintain this behavior) From there we instantiate the geometry with vertices and triangles.

```
this.viewer = new Viewer({
      divID: 'viewer',
      width: document.getElementById('viewer').offsetWidth,
      height: document.getElementById('viewer').offsetHeight,
      antiAlias: true,
      background: '#7A7AF3'
});

this.meshTopic.subscribe((msg: any) => {
     const geometry = new Geometry();
     msg.triangles.forEach(triangle => {
           const vt = triangle.vertex_indices;
           geometry.faces.push(new Face3(vt[0], vt[1], vt[2]));
      });

     msg.vertices.forEach(vertice => {
          geometry.vertices.push(new Vector3(vertice.x, vertice.y, vertice.z));
      });

      const threeMesh = new Mesh( geometry, new MeshBasicMaterial({ color: 0x999999 }));
      const mesh = new MeshResource({
          resource: 'none',
          warnings: true
      });

      mesh.add(threeMesh);
      mesh.scale.set(1, 1, 1);
      this.viewer.scene.add(mesh);
});
```

The initial rendering is fine.
![image](https://trial-test-data.s3.us-east-2.amazonaws.com/meshResourceBeforeViewerClick.png)
However once the user clicks the viewer object the mesh re-renders in a pipe shape
![image](https://trial-test-data.s3.us-east-2.amazonaws.com/meshResourceAfterViewerClick.png)

No matter what type of mesh is rendered it always changes into the same pipe shape once the viewer is clicked.

Any idea how I can resolve this issue?

**Comment by Sevilaa** [comment]
I'm running into the same error. What was your solution? Currently my only solution is to remove that object from the scene and add another one, bit it clearly shouldn't be that way.
