### ISSUE TITLE
URL errors in tutorial examples

### ISSUE THREAD

**Issue by petroslj** [RobotWebTools/ros3djs#293]
Example HTML code that references external URL resources seems to have numerous errors in both java script URLs and PR2 model URDF.  Context:
     Ubuntu 18.04 / ROS Melodic
     Tutorial 1: http://wiki.ros.org/ros3djs/Tutorials/VisualizingAURDF
     Tutorial 2: https://github.com/PacktPublishing/ROS-Robotics-Projects.git
Examples in both tutorials have bad java script URLs and cannot find & load PR2 URDF files.
Typical errors:
GET https://static.robotwebtools.org/threejs/current/STLLoader.min.js net::ERR_ABORTED 403
GET http://resources.robotwebtools.org/pr2_description/meshes/base_v0/base.dae net::ERR_NAME_NOT_RESOLVED

A screen shot of the javascript console errors is here:
![Screenshot from 2019-10-31 10-02-45](https://user-images.githubusercontent.com/56881794/67954731-ce512980-fbc7-11e9-9631-0da64bca7bda.png)

**Comment by msfarhan** [comment]
I'm also facing the same issue. I think path in urdf client which refers to resources.robotwebtools.org doesn't exist and hence we cannot load mesh .. I'm also looking for answers .. have you got any answers?

**Comment by chrisfernam2** [comment]
Hi any luck resolving this?

**Comment by MatthijsBurgh** [comment]
Examples have been updated. URDF resources are not hosted anymore.
