### ISSUE TITLE
urdf.html example not working.

### ISSUE THREAD

**Issue by Jhala420** [RobotWebTools/ros3djs#319]
I'm running ros3djs urdf.html example. But every time I got the following error. I search on google but I don't find any solution. 

![Screenshot from 2020-07-09 19-47-09](https://user-images.githubusercontent.com/40704141/87055149-66a2b200-c21d-11ea-8418-140b75519049.png)

The output of other commands are the following.

![Screenshot from 2020-07-09 20-04-32](https://user-images.githubusercontent.com/40704141/87060476-05caa800-c224-11ea-97dc-bf218a2547ea.png)
![Screenshot from 2020-07-09 20-04-35](https://user-images.githubusercontent.com/40704141/87060512-0ebb7980-c224-11ea-855e-a881dc43ab50.png)

![Screenshot from 2020-07-09 20-04-37](https://user-images.githubusercontent.com/40704141/87060541-15e28780-c224-11ea-8546-780880fee673.png)
![Screenshot from 2020-07-09 20-04-39](https://user-images.githubusercontent.com/40704141/87060570-1e3ac280-c224-11ea-9ffb-04b4dc0d618f.png)
![Screenshot from 2020-07-09 20-05-21](https://user-images.githubusercontent.com/40704141/87060583-2266e000-c224-11ea-8042-e6bf317091ec.png)
I have experience with ROS but I'm new to Robot Web Tool. 
ros2djs, roslibjs are working perfect.

I'm Using ROS Melodic.
Python 2.7.
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by MerAARIZOU** [comment]
Are you using a HTTP server? I see that you are opening HTML files in your browser. Try to install Apache server and put your HTML file and all the JS files then fix the URLs on your code

**Comment by Jhala420** [comment]
Thanks.
Problem Solved.
I Install the apache server and put files in it.
