### ISSUE TITLE
Load Collada files with build from current branch

### ISSUE THREAD

**Issue by aamirhatim** [RobotWebTools/ros3djs#330]
I have cloned the most recent version of the `develop` branch and built locally. I'm running into the issue where Collada files are not loading and I get the following console error: `TypeError: collada is undefined`

Error comes from line 51632 in `ros3d.esm.js`:
```javascript
// ......
// metadata

var version = collada.getAttribute('version');     // <----- ERROR OCCURS HERE -----
console.log('THREE.ColladaLoader: File version', version);

var asset = parseAsset(getElementsByTagName(collada, 'asset')[0]);
var textureLoader = new THREE$1.TextureLoader(this.manager);
textureLoader.setPath(path).setCrossOrigin(this.crossOrigin);

// ......
```
This occurs for all .dae I'm currently loading, which are coming from the HDL32e mesh files from the [velodyne_description](https://bitbucket.org/DataspeedInc/velodyne_simulator/src/master/velodyne_description/meshes/) package.

I double checked that I had the correct version of three installed as well (0.89.0), but it looks like `THREE.ColladaLoader` does not show up as a class if I try to load it manually. STL files load just fine.

If it helps, my current React app has the following dependencies in `package.json`:
```
"@testing-library/jest-dom": "^5.11.3",
"@testing-library/react": "^10.4.8",
"@testing-library/user-event": "^12.1.1",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "^3.4.3",
"ros2d": "^0.9.0",
"ros3d": "file:../../../../../npm/ros3djs",     // When running npm list ros3d, it returns version 1.0.1
"roslib": "^1.1.0",
"serve": "^11.3.2",
"three": "^0.89.0",
"typescript": "^4.0.2"
```
Any suggestions on getting around this are much appreciated!

**Comment by raphaelVig** [comment]
Hi,

Were you able to solve this issue ?

**Comment by aamirhatim** [comment]
Yes I no longer get this error. I didn't troubleshoot on my end so it must have been an external factor that fixed the issue for me. Thanks
