### ISSUE TITLE
URDF Example

### ISSUE THREAD

**Issue by zengkungan** [RobotWebTools/ros3djs#355]
There is no visualized robot in the window.
![image](https://user-images.githubusercontent.com/49355448/103840281-8a638980-50d4-11eb-97bd-6cc6e4f4588f.png)
something weird appeared.

**Comment by Martin-Oehler** [comment]
Have you checked the console?

**Comment by uahic** [comment]
Same issue here, it seems that the URDF resources (collada files?) on the robotwebtools server are not reachable or available at all  (see #293). Since 2017 this issue is still an issue :/
