### ISSUE TITLE
LaserScan does not display the points

### ISSUE THREAD

**Issue by amoula20** [RobotWebTools/ros3djs#356]
Hello,

I'm facing a problem with the laser scan display using ros3djs and rosbridge. when I record  a bagfile of the scan and run it on my laptop my browser display it perfectly, but when I try the same code on my jetson (nvidia nx) nothing displayed on the browser. and I tried to test the three.js & viewer from ros3djs by creating a simple Three JS cube and it was displayed. What am I missing here?

**Comment by city945** [comment]
Hi, I had the same problem. Did you solve it？

**Comment by MatthijsBurgh** [comment]
Stale
