### ISSUE TITLE
NavSatFix not included in most recent build

### ISSUE THREAD

**Issue by lax16** [RobotWebTools/ros3djs#415]
The NavSatFix feature is not included in the most recent build 5bf7b39cda9afa795a733ae04c30310e1d3c906c . This is due to it not being included in the index.js file. I don't know if this was an intentional choice but if it isn't then it's easily fixable by including NavSatFix in index.js.

**Comment by MatthijsBurgh** [comment]
Lets if the CI succeeds of #416
