### ISSUE TITLE
Pixel flickering when rendering point cloud on iPhone

### ISSUE THREAD

**Issue by Jaetriel** [RobotWebTools/ros3djs#466]
**Description**

I am rendering a 3D point cloud map from a LiDAR and I've tested it on Android, a Windows laptop and and an Iphone 12. On the Iphone I get these weird flickering pixels that appear like they are rendered right in front of the camera and it makes the viewing experience really poor
![image0](https://user-images.githubusercontent.com/43788971/141121218-abaca66c-f148-4623-bf6d-aefde1b128ce.png)
![image1](https://user-images.githubusercontent.com/43788971/141121225-3f3599b3-fb34-43ac-bc1b-6a903e221428.png)
![image2](https://user-images.githubusercontent.com/43788971/141121228-69130500-97c0-47c1-a74a-a0d3eecc1a8d.png)
![image3](https://user-images.githubusercontent.com/43788971/141121232-0d295cda-fe88-458b-91a1-2bda20f7c5f8.png)

- Library Version: 1.01
- ROS Version: Melodic
- Platform / OS: Host machine running the SLAM + web server is an NVidia Jetson Xavier AGX with Jetson OS based on Ubuntu 18.04

**Steps To Reproduce**

This is the cloudClient code I used to add the point cloud to the scene: 
`var cloudClient = new ROS3D.PointCloud2({
       ros: ros,
       tfClient: tfClient,
       rootObject: viewer.scene,
       topic: '/cloud_registered',
       material: {size: 0.1, color: 0xffffff},
       decay: 1000,
       max_pts: 50000000,
       messageRation: 10,
});`
The `decay` option comes from PR #357 

**Expected Behavior**
The points should be rendered without any flickering pixels

**Comment by MatthijsBurgh** [comment]
As we mostly wrap Three, I think its better to open an issue there. I think our support doesn't reach iPhone.

**Comment by Jaetriel** [comment]
@MatthijsBurgh thank you I will close this then and turn to three.js support
