### ISSUE TITLE
Problem with the API Documentation Page

### ISSUE THREAD

**Issue by Felix-Tr** [RobotWebTools/ros3djs#547]
Same Case as in https://github.com/RobotWebTools/ros3djs/issues/476 but both Links aren't available:
http://robotwebtools.org/ros3djs/
http://robotwebtools.org/jsdoc/ros3djs/current/
also all linked versions in the ros wiki (http://wiki.ros.org/ros3djs) aren't available, can anybody help?

**Comment by MatthijsBurgh** [comment]
I discovered it wasn't working anymore this morning, see https://github.com/RobotWebTools/robotwebtools.org/issues/81

Please be patient. You can still clone the repo and generate the docs yourself.

**Comment by Felix-Tr** [comment]
Alright, I'll wait for the fix and close the issue then. Thanks for the fast response!
