### ISSUE TITLE
PointCloud2 is not display ﻿

### ISSUE THREAD

**Issue by dyjandxy** [RobotWebTools/ros3djs#692]
I have a relatively large point cloud data with max_pts set to a maximum of 150000000. PointCloud2 loads the latest data every time and cleans up the old data. How to make the data load and display every time

**Comment by MatthijsBurgh** [comment]
Your message is contradicting. You say it drops the old data and loads the new data. Which is the desired behaviour IMO.
Though you also ask how to load the data and display it.
So what is the real question?

Also share some code if you want people to help you.

Just start by using the [example](https://github.com/RobotWebTools/ros3djs/blob/develop/examples/depthcloud.html). Adapt it to your needs.

**Comment by dyjandxy** [comment]
This is the code for me to load point cloud according to the official example
![1](https://github.com/user-attachments/assets/2f6eae2c-ed83-4b9a-b0d5-2119864c2c40)
This is the source code of PointCloud2 that I reviewed. This code updates the latest received data every time, and old data is replaced
![2](https://github.com/user-attachments/assets/1da9a78f-ba15-4c0f-9056-7525034c27c6)
![3](https://github.com/user-attachments/assets/f1542513-b75a-4f91-84cb-a068490cde7b)
If I want new data to accumulate and display data without replacing old data, I should need to change the source code of PointCloud2
My data is pushed repeatedly, and the new data pushed each time does not include the data that has already been pushed. However, I am not sure how to push new data that includes the data that has already been pushed
