### ISSUE TITLE
ColladaLoader2 Repeated Mesh Loading

### ISSUE THREAD

**Issue by DLu** [RobotWebTools/ros3djs#70]
Forked discussion from #69.

When updating interactive markers, ColladaLoader reloads the meshes repeatedly, even if they have not changed, and the garbage collection can not keep up. 

Here is a simple package that demonstrates the problem.
http://www.cse.wustl.edu/~dvl1/stuff/marker_marker_marker.zip

Just run the launch file and open the html file in a browser. Note the memory seems to grow if you change the marker to a simple geometry like a cube, although much more slowly for obvious reasons.

**Comment by jihoonl** [comment]
ColladaLoader2 has been removed from upstream version.
