### ISSUE TITLE
load objects in the scene

### ISSUE THREAD

**Issue by fredrabelo** [RobotWebTools/ros3djs#95]
hey guys, is there a way I can load objects into the scene? say a table.urdf?

**Comment by rctoris** [comment]
Can you give more details on what you mean by something like table.urdf? 3D objects can be added to the scene via this method as well: https://github.com/RobotWebTools/ros3djs/blob/develop/src/visualization/Viewer.js#L116

**Comment by DLu** [comment]
Close for inactivity?
